spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

basic:
  ribbon:
    eureka:
      enabled: false
    NIWSServerListClassName: com.bebra.oscarserver.configuration.ConsulServerList
    ServerListRefreshInterval: 1000

ribbon:
  client:
    name: client
