spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

oscar-server:
  ribbon:
    eureka:
      enabled: false
    NIWSServerListClassName: org.bebra.oscarserver.configuration.ConsulServerList
    ServerListRefreshInterval: 1000

ribbon:
  client:
    name: client
